- name: registering vrs
  hosts: all
  tasks:
   - name: print that uptime
     shell: uptime
     register: OUT


   - name: print out
     debug:
       msg: "{{OUT.stdout}}"


   - name: print present working directory
     shell: pwd
     register: WORK


   - name: print pwd
     debug: 
       msg: "{{WORK.stdout}}"
